# Generated by Django 6.0.6 on 2026-06-12 11:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LostFoundItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('category', models.CharField(choices=[('Electronics', 'Electronics'), ('ID', 'ID'), ('Wallet', 'Wallet'), ('Keys', 'Keys'), ('Bag', 'Bag'), ('Other', 'Other')], max_length=20)),
                ('description', models.TextField(max_length=200)),
                ('location', models.CharField(max_length=50)),
                ('date_lost_found', models.DateField()),
                ('status', models.CharField(choices=[('Lost', 'Lost'), ('Found', 'Found'), ('Claimed', 'Claimed')], max_length=20)),
                ('contact_info', models.CharField(max_length=11)),
                ('image', models.ImageField(upload_to='items/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
